# Generated by Django 5.1.4 on 2024-12-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_timestamp_course_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public_id',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
