# Generated by Django 5.1.4 on 2024-12-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_rating_coursereviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereviews',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course Review'},
        ),
    ]
