# Generated by Django 5.1.4 on 2024-12-31 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_coursereviews_options'),
        ('emails', '0007_email_cart_items_email_favorites_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseReviews',
            new_name='CourseReview',
        ),
        migrations.CreateModel(
            name='LessonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.email')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Course Review',
                'ordering': ['-created_at'],
            },
        ),
    ]
