# Generated by Django 5.1.4 on 2024-12-30 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_rating'),
        ('emails', '0003_emailverificationevent_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.ManyToManyField(blank=True, related_name='cart_users', to='courses.course')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_users', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emails.email')),
            ],
        ),
    ]
