# Generated by Django 5.1.4 on 2024-12-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_coursereviews_options'),
        ('emails', '0005_userprofile_lesson_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lesson_favorites',
            field=models.ManyToManyField(blank=True, related_name='lesson_favorite_users', to='courses.lesson'),
        ),
    ]
