# Generated by Django 5.1.4 on 2024-12-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_coursereviews_options'),
        ('emails', '0006_alter_userprofile_lesson_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='cart_users', to='courses.course'),
        ),
        migrations.AddField(
            model_name='email',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='courses.course'),
        ),
        migrations.AddField(
            model_name='email',
            name='lesson_favorites',
            field=models.ManyToManyField(blank=True, related_name='lesson_favorite_users', to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
